version: '3.9'

services:
  api:
    depends_on:
      - db
    build:
      context: ./API
    ports:
      - "3000:80"
    networks:
      - internal_network
    volumes:
      - ./API/src:/var/www/html

  thread:
    depends_on:
      - api
    build:
      context: ./Thread
    ports:
      - "8000:80"
    networks:
      - internal_network
    volumes:
      - ./Thread:/usr/share/nginx/html

  sender:
    depends_on:
      - api
    build:
      context: ./Sender
    ports:
      - "8080:80"
    networks:
      - internal_network
    volumes:
      - ./Sender:/usr/share/nginx/html

  apache:
    image: php:7.4-apache
    volumes:
      - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "3001:80"
    depends_on:
      - api
    networks:
      - internal_network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: joueur_stats_db
      MYSQL_USER: user
      MYSQL_PASSWORD: mdp
    networks:
      - internal_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  internal_network:

volumes:
  db_data:
