FROM mysql:latest

ENV MYSQL_HOST=localhost
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=joueur_stats_db
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=mdp

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306

CMD ["mysql"]